# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-08-02 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='用户名')),
                ('nickname', models.CharField(max_length=50, verbose_name='昵称')),
                ('e_mail', models.EmailField(max_length=50, verbose_name='E_mail')),
                ('sign', models.CharField(max_length=150, verbose_name='个人签名')),
                ('password', models.CharField(max_length=100, verbose_name='密码')),
                ('info', models.CharField(max_length=100, verbose_name='个人信息')),
                ('avatar', models.ImageField(null=True, upload_to='avatar/', verbose_name='头像')),
            ],
        ),
    ]
