# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-15 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_book_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='id',
        ),
        migrations.AddField(
            model_name='book',
            name='auther',
            field=models.CharField(default='', max_length=50, verbose_name='作者'),
        ),
        migrations.AddField(
            model_name='book',
            name='pub_date',
            field=models.DateField(default='2017-1-1', verbose_name='出版时间'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='书名'),
        ),
    ]
