# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-18 02:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('many2many', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book3',
            name='authors',
            field=models.ManyToManyField(to='many2many.Auther3'),
        ),
    ]
