# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-17 08:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='姓名')),
                ('age', models.IntegerField(max_length=20, verbose_name='年龄')),
            ],
        ),
        migrations.CreateModel(
            name='Wife',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='姓名')),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='market_price',
            field=models.DecimalField(decimal_places=2, default=9999, max_digits=7, verbose_name='零售价:'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='定价:'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pub_house',
            field=models.CharField(default='', max_length=100, verbose_name='出版社:'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(default='untitled', max_length=50, verbose_name='书名:'),
        ),
        migrations.AddField(
            model_name='wife',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bookstore.Book'),
        ),
    ]
