# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-17 10:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_auto_20190717_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wife',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bookstore.Author'),
        ),
    ]
